version: "3.7"

services:
  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
  
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - my.cnf:/etc/mysql/conf.d

  worker:
    build: .
    depends_on:
      - redis
    command: "celery -A worker.celery_worker worker -l info"
  
  beat:
    build: .
    depends_on:
      - redis
    command: "celery -A worker.celery_worker beat -l info"