version: "3.7"

services:
  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    command: "celery -A app.worker.celery_worker worker -l info"
  
  beat:
    build: .
    depends_on:
      - redis
    command: "celery -A app.worker.celery_worker beat -l info"